INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (10,'Estación de La Coruña','A Coruña','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (151,'Estación Central de Aachen','Aachen','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (30,'Estación de Albacete-Los Llanos','Albacete','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (7,'Estación de Albufeira-Ferreiras','Albufeira','Portugal');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (31,'Estación de Alicante','Alicante','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (28,'Estación de Almería','Almería','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (105,'Estación Central de Amersfoort','Amersfoort','Holanda');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (64,'Estación de Amiens','Amiens','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (100,'Estación Central de Amsterdam','Amsterdam','Holanda');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (122,'Estación de Ancona','Ancona','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (94,'Estación Central de Antwerpen','Antwerpen','Bélgica');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (104,'Estación Central de Arnhem','Arnhem','Holanda');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (140,'Estación Central de Augsburg','Augsburg','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (51,'Estación de Avignon TGV','Avignon','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (23,'Estación de Badajoz','Badajoz','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (34,'Estación de Barcelona Sants','Barcelona','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (115,'Estación Central de Bari','Bari','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (110,'Estación de Basel SBB','Basel','Suiza');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (39,'Estación de Bayonne','Bayonne','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (167,'Estación de Bebra','Bebra','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (176,'Estación Central de Berlin','Berlin','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (109,'Estación de Bern','Bern','Suiza');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (72,'Estación de Besancon','Besancon','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (44,'Estación de Béziers','Béziers','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (19,'Estación de Bilbao','Bilbao','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (81,'Estación de Birmingham New Street','Birmingham','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (124,'Estación Central de Bologna','Bologna','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (131,'Estación de Bolzano','Bolzano','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (152,'Estación Central de Bonn','Bonn','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (42,'Estación de Bordeaux-Saint-Jean','Bordeaux','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (1,'Estacion de Braga','Braga','Portugal');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (177,'Estación Central de Braunschweig','Braunschweig','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (180,'Estación Central de Bremen','Bremen','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (56,'Estación de Brest-Tsentralny','Brest','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (113,'Estación de Brindisi','Brindisi','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (78,'Estación Bristol Temple Meads','Bristol','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (91,'Estación de Brugge','Brugge','Bélgica');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (93,'Estación Central de Bruxelles','Bruxelles','Bélgica');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (17,'Estación de Burgos Rosa de Lima','Burgos','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (25,'Estación de Cádiz','Cádiz','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (59,'Estación de Caen','Caen','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (79,'Estación Central de Cardiff','Cardiff','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (33,'Estación de Castellón de la Plana','Castellón','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (70,'Estación de Charleville Mézieres','Charleville Mézieres','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (169,'Estación Central de Chemnitz','Chemnitz','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (53,'Estación de Clermont-Ferrand','Clermont-Ferrand','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (6,'Estacion de Coimbra','Coimbra','Portugal');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (24,'Estación de Córdoba','Córdoba','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (172,'Estación Central de Cottbus','Cottbus','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (146,'Estación Central de Darmstadt','Darmstadt','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (101,'Estación Central de Den Haag','Den Haag','Holanda');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (173,'Estación Central de Dessau','Dessau','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (71,'Estación de Dijon-Ville','Dijon','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (160,'Estación Central de Dortmund','Dortmund','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (170,'Estación Central de Dresden','Dresden','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (156,'Estación Central de Duisburg','Duisburg','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (155,'Estación Central de Dusseldorf','Dusseldorf','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (88,'Estación de Edinburgh Waverley','Edinburgh','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (106,'Estación Central de Eindhoven','Eindhoven','Holanda');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (165,'Estación Central de Erfurt','Erfurt','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (157,'Estación Central de Essen','Essen','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (5,'Estacion de Faro','Faro','Portugal');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (123,'Estación de Firenze Santa Maria Novella','Firenze','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (116,'Estación de Foggia','Foggia','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (150,'Estación Central de Frankfurt','Frankfurt','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (136,'Estación Central de Freiburg','Freiburg','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (166,'Estación de Fulda','Fulda','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (107,'Estación de Geneve-Cornavin','Geneve','Suiza');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (134,'Estación de Genova Piazza Principe','Genova','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (92,'Estación de Gent-Sint-Pieters','Gent','Bélgica');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (13,'Estación de Gijón','Gijón','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (89,'Estación de Glasgow Central','Glasgow','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (27,'Estación de Granada','Granada','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (55,'Estación de Grenoble','Grenoble','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (98,'Estación de Groningen','Groningen','Holanda');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (2,'Estación de Guimarães','Guimarães','Portugal');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (159,'Estación Central de Hagen','Hagen','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (181,'Estación Central de Hamburg','Hamburg','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (163,'Estación Central de Hannover','Hannover','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (144,'Estación Central de Heidelberg','Heidelberg','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (164,'Estación Jena Paradies','Jena','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (137,'Estación Central de Karlsruhe','Karlsruhe','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (162,'Estación Central de Kassel','Kassel','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (183,'Estación Central de Kiel','Kiel','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (154,'Estación Central de Koln','Koln','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (127,'Estación Central de La Spezia','La Spezia','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (108,'Estación de Lausanne ','Lausanne','Suiza');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (60,'Estación de Le Havre','Le Havre','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (61,'Estación de Le Mans','Le Mans','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (85,'Estación de Leeds','Leeds','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (171,'Estación Central de Leipzig','Leipzig','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (14,'Estación de León','León','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (96,'Estación de Liege-Guillemins','Liege','Bélgica');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (63,'Estación de Lille','Lille','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (43,'Estación de Limoges-Bénédictins','Limoges','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (4,'Estacion de Oriente','Lisboa','Portugal');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (82,'Estación Liverpool Lime Street','Liverpool','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (125,'Estación Central de Livorno','Livorno','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (35,'Estación de Lleida','Lleida','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (77,'Estación King\'s Cross','London','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (182,'Estación Central de Lubeck','Lubeck','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (112,'Estación de Lugano','Lugano','Suiza');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (97,'Estación de Luxemburgo','Luxemburgo','Luxemburgo');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (52,'Estación de Lyon-Part-Dieu','Lyon','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (95,'Estación de Maastricht','Maastricht','Bélgica');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (22,'Estación de Atocha','Madrid','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (174,'Estación Central de Magdeburg','Magdeburg','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (149,'Estación Central de Mainz','Mainz','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (26,'Estación de Málaga-María Zambrano','Málaga','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (83,'Estación Manchester Piccadilly','Manchester','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (148,'Estación Central de Mannheim','Mannheim','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (47,'Estación de Marseille-Saint-Charles','Marseille','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (74,'Estación de Metz-Ville','Metz','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (133,'Estación Central de Milano','Milano','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (153,'Estación Central de Monchen-Gladbach','Monchen-Gladbach','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (45,'Estación de Montpellier-Saint-Roch','Montpellier','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (73,'Estación de Mulhouse-Ville','Mulhouse','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (141,'Estación Central de Munchen','Munchen','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (29,'Estación de Murcia del Carmen','Murcia','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (75,'Estación de Nancy-Ville','Nancy','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (57,'Estación de Nantes','Nantes','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (118,'Estación Central de Napoli','Napoli','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (87,'Estación de Newcastle','Newcastle','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (54,'Estación de Nice-Ville','Nice','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (46,'Estación de Nimes','Nimes','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (143,'Estación Central de Nurnberg','Nurnberg','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (90,'Estación de Oostende','Oostende','Bélgica');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (67,'Estación de Orléans','Orléans','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (161,'Estación Central de Osnabruck','Osnabruck','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (11,'Estación de Ourense-Empalme','Ourense','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (12,'Estación de Oviedo','Oviedo','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (130,'Estación de Padova','Padova','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (21,'Estación de Pamplona','Pamplona','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (66,'Estación de Paris Nord','Paris','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (40,'Estación de Pau','Pau','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (38,'Estación de Perpignan','Perpignan','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (121,'Estación de Perugia','Perugia','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (119,'Estación Central de Pescara','Pescara','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (126,'Estación Central de Pisa','Pisa','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (3,'Estación de Porto-Sao-Bento','Porto','Portugal');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (175,'Estación Central de Potsdam','Potsdam','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (142,'Estación Central de Regensburg','Regensburg','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (68,'Estación de Reims','Reims','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (58,'Estación de Rennes','Rennes','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (120,'Estación Roma Termini','Roma','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (178,'Estación Central de Rostock','Rostock','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (102,'Estación Central de Rotterdam','Rotterdam','Holanda');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (65,'Estación de Rouen-Rive-Droite','Rouen','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (147,'Estación Central de Saarbrucken','Saarbrucken','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (15,' Estación de Salamanca','Salamanca','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (117,'Estación de Salerno','Salerno','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (20,'Estación de San Sebastián','San Sebastián','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (18,'Estación de Santander','Santander','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (9,'Estación de Santiago de Compostela','Santiago de Compostela','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (179,'Estación Central de Schwerin','Schwerin','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (36,'Estación de Sevilla-Santa-Justa','Sevilla','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (84,'Estación de Sheffield','Sheffield','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (50,'Estación de St. Étienne-Chateaucreux','St. Étienne','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (76,'Estación de Strasbourg-Ville','Strasbourg','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (138,'Estación Central de Stuttgart','Stuttgart','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (80,'Estación de Swansea','Swansea','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (114,'Estación de Taranto','Taranto','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (135,'Estación de Torino Porta Nuova','Torino','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (48,'Estación de Toulon','Toulon','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (41,'Estación de Toulouse-Matabiau','Toulouse','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (62,'Estación de Tours','Tours','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (128,'Estación Central de Trieste','Trieste','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (69,'Estación de Troyes','Troyes','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (139,'Estación Central de Ulm','Ulm','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (103,'Estación Central de Utrecht','Utrecht','Holanda');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (49,'Estación de Valence TGV','Valence','Francia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (32,'Estación de Valencia-Norte','Valencia','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (16,'Estación de Valladolid-Campo Grande','Valladolid','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (129,'Estación de Venezia Santa Lucia','Venezia','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (132,'Estación de Verona Porta Nuova','Verona','Italia');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (8,'Estación de Vigo-Urzáiz','Vigo','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (158,'Estación Central de Wuppertal','Wuppertal','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (145,'Estación Central de Wurzburg','Wurzburg','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (86,'Estación de York','York','Gran Bretaña');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (37,'Estación de Zaragoza-Delicias','Zaragoza','España');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (111,'Estación Central de Zurich','Zurich','Suiza');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (168,'Estación Central de Zwickau','Zwickau','Alemania');
INSERT INTO estacion (estacion_id,nombre,ciudad,pais) VALUES (99,'Estación de Zwolle','Zwolle','Holanda');
